### ISSUE TITLE
Docker run failed to run

### ISSUE THREAD

**Issue by camilogarciabotero** [metagenlab/locus2genoplotr#1]
Hi all,

I was trying to make some arrow diagrams using {locus2genoplotr} and found an error with the example command you provided when running from docker:

`docker run metagenlab/locus2genoplotr:1.1 locus2genoplotr -l KL24_00002 -r data/K24.gbk -o single_plot -v `

```
Traceback (most recent call last):
  File "/opt/conda/envs/locus2genoplotr/bin/locus2genoplotr", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/locus2genoplotr/lib/python3.8/site-packages/locus2genoplotr/__init__.py", line 24, in main
    L = locus2genoplotr.Locus2genoplotR(args.locus,
  File "/opt/conda/envs/locus2genoplotr/lib/python3.8/site-packages/locus2genoplotr/locus2genoplotr.py", line 39, in __init__
    self.reference_record = [i for i in SeqIO.parse(open(reference_genbank), 'genbank')]
FileNotFoundError: [Errno 2] No such file or directory: 'data/K24.gbk'
```

It seems it is not recognizing the path (I also tried the absolute path). Maybe you can help me with this.

Cheers,
Camilo.

**Comment by camilogarciabotero** [comment]
Hi again,

Well it was actually a problem with setting the volume on the docker image (am quite new with Docker), my solution was just:

```
docker run -v `pwd`:`pwd` -w `pwd` -i -t metagenlab/locus2genoplotr:1.1 locus2genoplotr -l KL24_00002 -r data/K24.gbk -o single_plot
```

and got a beautiful plot.
